#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitaly
  namespace: #@ data.values.gitlab.namespace
spec:
  replicas: 1
  selector:
    matchLabels: #@ data.values.gitlab.gitaly.matchLabels
  template:
    metadata:
      labels: #@ data.values.gitlab.gitaly.matchLabels
    spec:
      containers:
      - name: main
        image: #@ "gitlab/gitlab-ce:{}-ce.0".format(data.values.gitlab.version)
        env:
        - name: GITLAB_OMNIBUS_CONFIG
          valueFrom:
            configMapKeyRef:
              name: gitaly
              key: GITLAB_OMNIBUS_CONFIG
        ports:
        - name: gitaly
          containerPort: 8075
        volumeMounts:
        - mountPath: "/var/opt/gitlab"
          name: gitaly
          subPath: gitaly-data
        - mountPath: "/etc/gitlab"
          name: gitaly
          subPath: gitaly-config
        - mountPath: "/var/log/gitlab"
          name: gitaly
          subPath: gitaly-log
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
      - name: gitaly
        emptyDir: {}
      - name: tz-config
        hostPath:
          path: #@ "/usr/share/zoneinfo/" + data.values.timezone
