#@data/values
---
#@overlay/match missing_ok=True
timezone: Europe/Berlin
#@overlay/match missing_ok=True
domain: example.com
#@overlay/match missing_ok=True
openldap:
  namespace: openldap
  domain:
    dn: dc=example,dc=com
  matchLabels:
    app: openldap
  password:
    config: test123
    admin: test123
  dns:
    name: openldap
    lb: lb
#@overlay/match missing_ok=True
phpldapadmin:
  namespace: openldap
  matchLabels:
    app: phpldapadmin
  dns:
    name: phpldapadmin
    lb: lb
