#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare
  namespace: #@ data.values.traefik.namespace
type: Opaque
stringData:
  CF_API_EMAIL: #@ data.values.cloudflare.email
  CF_API_KEY: #@ data.values.cloudflare.key
