#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-grafana
  namespace: #@ data.values.grafana.namespace
spec:
  replicas: 1
  selector:
    matchLabels: #@ data.values.grafana.db.matchLabels
  template:
    metadata:
      labels: #@ data.values.grafana.db.matchLabels
    spec:
      restartPolicy: Always
      containers:
      - name: mysql-grafana
        image: mysql
        imagePullPolicy: Always
        env:
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "true"
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: grafana
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: grafana
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-pass
              name: grafana
        ports:
        - containerPort: 3306
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/mysql/conf.d/
          name: config
      volumes:
      - configMap:
          name: mysql-grafana
        name: config
