#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-authenticator
  namespace: #@ data.values.k8sauth.namespace
spec:
  secretName: certificate-k8sauth
  duration: 2160h
  renewBefore: 360h
  commonName: #@ "{}.{}".format(data.values.k8sauth.dns.name, data.values.domain)
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
  - digital signature
  - key encipherment
  dnsNames:
  - #@ "{}.{}".format(data.values.k8sauth.dns.name, data.values.domain)
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
