---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8sauth
  namespace: dex
spec:
  secretName: certificate-k8sauth
  duration: 2160h
  renewBefore: 360h
  commonName: auth.dille.io
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
  - digital signature
  - key encipherment
  dnsNames:
  - auth.dille.io
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
