---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dex-k8s-authenticator
  namespace: dex
  labels:
    app: dex-k8s-authenticator
data:
  config.yaml: |-
    listen: http://0.0.0.0:5555
    web_path_prefix: /
    debug: false
    #logo_uri: {{ .logoUrl }}
    clusters:
    - name: dilleio
      short_description: "My Cluster"
      description: "Example Cluster Long Description..."
      client_secret: test123
      issuer: https://dex.dille.io
      k8s_master_uri: https://78.47.163.162:6443
      client_id: k8sauth
      redirect_uri: https://auth.dille.io/callback/dilleio
      #k8s_ca_uri: https://url-to-your-ca.crt
      #k8s_ca_pem: |
