#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-authenticator
  namespace: #@ data.values.k8sauth.namespace
  labels: #@ data.values.k8sauth.matchLabels
data:
  #@yaml/text-templated-strings
  config.yaml: |-
    listen: http://0.0.0.0:5555
    web_path_prefix: /
    debug: false
    #logo_uri: {{ .logoUrl }}
    clusters:
    - name: k8sauth
      short_description: "My Cluster"
      description: "Example Cluster Long Description..."
      client_secret: test123
      issuer: https://(@= data.values.dex.dns.name @).(@= data.values.domain @)
      k8s_master_uri: https://78.47.163.162:6443
      client_id: k8sauth
      redirect_uri: https://(@= data.values.k8sauth.dns.name @).(@= data.values.domain @)/callback/k8sauth
      scope:
      - openid
      debug: true
      k8s_ca_pem: |
        -----BEGIN CERTIFICATE-----
        MIICyDCCAbCgAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
        cm5ldGVzMB4XDTIwMDQwMjIxMDUyM1oXDTMwMDMzMTIxMDUyM1owFTETMBEGA1UE
        AxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANVU
        c94OX86cxx7oWkSc/+plm7FKMrwLtXKREGQZL0lmjLZ9Fd6y8ni/L0hXuARCdbRc
        sRkDtI2CU8m/uSswYoJ3Hve0HP6YCf9Tg9rmbCXdEPGmjLorF2BFzZs/10UP90ru
        a7A998wZ4NPwZwAdW2k5tWOQS+vQ2pCyCQNqA//NVrLrGin2etiv9n0yOtuoM860
        wQgM1XKRLQHcUuPAiUHKvjZYpTO/W2qE4o/1J+5sag+0MtRuf+5U24n4LR5lg1u+
        yJeA3k0ENiUFGv3N0NTfHZ36sGxcVc/GMxA0MmxYyYy1CO3k1KALWzlu6sL1d+cn
        7/XOc/f6DqWxoPPcn5UCAwEAAaMjMCEwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB
        /wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAEPicVjVi/dL20/dA5cHlC1BFvI3
        N1BhE5sdNxECGpL4DUnWusmRQfywWUiaDCovRR41anzR86q2YOnVoiptEBhAMmG2
        KGKzoLMG8SHyALRVbS/Y350haEvRvcdmb3o5jL/aA4beCC5qcv1taMj1WFYJ948r
        oNMKPYwFDL75cDj/kzYG3tfsjR848VkWFTwKirtLty4Lw6cE3DR3wMbWVm2qZbGC
        hKqFqF/MkKdT/LyNcfPSDlHFQUWuCcRr26Udba9hAaky7/KgnVLhrtAqymvcnHoy
        OWk2dzD9WclQUJoWZaqT6oJlD2hKE8cueFaUCGPeX0jSy79TuECQ4j1BSSI=
        -----END CERTIFICATE-----
