---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: k8sauth
  namespace: dex
spec:
  endpoints:
  - dnsName: auth.dille.io
    recordTTL: 180
    recordType: CNAME
    targets:
    - lb.dille.io
