---
apiVersion: v1
kind: Service
metadata:
  name: dex-k8s-authenticator
  namespace: dex
  labels:
    app: dex-k8s-authenticator
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5555
    targetPort: 5555
    protocol: TCP
  selector:
    app: dex-k8s-authenticator
