---
# Source: vault-secrets-webhook/templates/webhook-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-secrets-webhook
  namespace: default
  labels:
    helm.sh/chart: vault-secrets-webhook-0.8.0
    app.kubernetes.io/name: vault-secrets-webhook
    app.kubernetes.io/instance: vault-secrets-webhook
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mutating-webhook
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-secrets-webhook
      app.kubernetes.io/instance: vault-secrets-webhook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vault-secrets-webhook
        app.kubernetes.io/instance: vault-secrets-webhook
        security.banzaicloud.io/mutate: skip
      annotations:
        checksum/config: bb0686c888201365a8c48d2b3bbcf2811d7c9b894116f17fd6e8bd98340d98bf
    spec:
      serviceAccountName: vault-secrets-webhook
      volumes:
        - name: serving-cert
          secret:
            defaultMode: 420
            secretName: vault-secrets-webhook
      containers:
        - name: vault-secrets-webhook
          image: "banzaicloud/vault-secrets-webhook:0.9.0"
          env:
            - name: TLS_CERT_FILE
              value: /var/serving-cert/tls.crt
            - name: TLS_PRIVATE_KEY_FILE
              value: /var/serving-cert/tls.key
            - name: LISTEN_ADDRESS
              value: ":8443"
            - name: DEBUG
              value: "false"
            - name: VAULT_ENV_IMAGE
              value: "banzaicloud/vault-env:0.9.0"
            - name: VAULT_IMAGE
              value: "vault:1.3.1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: 8443
          volumeMounts:
            - mountPath: /var/serving-cert
              name: serving-cert
          securityContext:
            runAsUser: 65534
            allowPrivilegeEscalation: false
          resources:
            {}
