---
# Source: vault-secrets-webhook/templates/webhook-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: vault-secrets-webhook
---
# Source: vault-secrets-webhook/templates/webhook-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-secrets-webhook
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - "get"
      - "update"
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - "create"
      - "update"
---
# Source: vault-secrets-webhook/templates/webhook-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-secrets-webhook-limited
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: vault-secrets-webhook
subjects:
- kind: ServiceAccount
  namespace: default
  name: vault-secrets-webhook
