#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: #@ data.values.drone.namespace
spec:
  replicas: 1
  selector:
    matchLabels: #@ data.values.drone.matchLabels
  template:
    metadata:
      labels: #@ data.values.drone.matchLabels
    spec:
      containers:
      - name: main
        image: #@ "drone/drone:{}".format(data.values.drone.version)
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 80
        - name: other
          containerPort: 9000
        env:
        - name: DRONE_RPC_SECRET
          value: #@ data.values.drone.secret
        - name: DRONE_SERVER_HOST
          value: #@ data.values.drone.fqdn
        - name: DRONE_SERVER_PROTO
          value: "http"
        - name: DRONE_USER_CREATE
          value: #@ "username:{},machine:false,admin:true,token:{}".format("admin", data.values.drone.admin.password)
        volumeMounts:volumes:
        - name: drone-data
          emptyDir: {}
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
      - name: drone-data
        mountPath: "/var/lib/drone"
      - name: tz-config
        hostPath:
          path: #@ "/usr/share/zoneinfo/" + data.values.timezone
