#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: #@ data.values.traefik.namespace
  annotations:
    external-dns.alpha.kubernetes.io/hostname: #@ data.values.traefik.lb
spec:
  selector:
    app: traefik
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: None
