#@ load("@ytt:data", "data")
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  #@yaml/text-templated-strings
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "(@= data.values.domain @)/node-type=loadbalancer,(@= data.values.domain @)/(@= data.values.traefikinitdns.label_name @)=(@= data.values.kind.master.ip @)"
        authorization-mode: "AlwaysAllow"
  #@yaml/text-templated-strings
  - |
    kind: ClusterConfiguration
    apiServer:
      certSANs:
      - k8s.(@= data.values.domain @)
      - 127.0.0.1
      - (@= data.values.kind.master.ip @)
      extraArgs:
        oidc-issuer-url: https://(@= data.values.dex.dns.name @).(@= data.values.domain @)
        oidc-client-id: gangway
        oidc-username-claim: email
        oidc-groups-claim: groups
  #@yaml/text-templated-strings
  - |
    kind: KubeProxyConfiguration
    metricsBindAddress: "0.0.0.0:10249"
  #@yaml/text-templated-strings
  - |
    extraMounts:
    - hostPath: /local-path-provisioner
      containerPath: /var/local-path-provisioner
  extraPortMappings:
  - containerPort: 6443
    hostPort: 6443
  - containerPort: 80
    hostPort: 80
  - containerPort: 443
    hostPort: 443
- role: worker
