#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: dex
  namespace: #@ data.values.dex.namespace
spec:
  secretName: certificate-dex
  duration: 2160h
  renewBefore: 360h
  commonName: #@ "{}.{}".format(data.values.dex.dns.name, data.values.domain)
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
  - digital signature
  - key encipherment
  dnsNames:
  - #@ "{}.{}".format(data.values.dex.dns.name, data.values.domain)
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer