#@ load("@ytt:data", "data")
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dex
  namespace: #@ data.values.dex.namespace
data:
  #@yaml/text-templated-strings
  config.yaml: |
    issuer: https://(@= data.values.dex.dns.name @).(@= data.values.domain @)

    storage:
      type: kubernetes
      config:
        inCluster: true

    web:
      http: 0.0.0.0:5556

    #frontend:
    #  theme: "coreos"
    #  issuer: "Example Co"
    #  issuerUrl: "https://example.com"
    #  logoUrl: https://example.com/images/logo-250x25.png
      
    #expiry:
    #  signingKeys: "6h"
    #  idTokens: "24h"

    connectors:
    - type: gitlab
      id: gitlab
      name: gitlab
      config:
        baseURL: https://gitlab.haufedev.systems
        clientID: $GITLAB_APPLICATION_ID
        clientSecret: $GITLAB_CLIENT_SECRET
        redirectURI: https://(@= data.values.dex.dns.name @).(@= data.values.domain @)/callback
        useLoginAsID: false

    staticClients:
    - id: (@= data.values.gangway.client.id @)
      redirectURIs:
      - https://(@= data.values.gangway.dns.name @).(@= data.values.domain @)/callback
      name: "(@= data.values.gangway.client.id @)"
      secret: (@= data.values.gangway.client.secret @)
    - id: k8sauth
      redirectURIs:
      - https://(@= data.values.k8sauth.dns.name @).(@= data.values.domain @)/callback/k8sauth
      name: k8sauth
      secret: test123

    enablePasswordDB: true
    staticPasswords:
    - email: "admin@(@= data.values.domain @)"
      hash: "(@= data.values.dex.admin.password @)"
      username: "admin"
      userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
