#@ load("@ytt:data", "data")
---
kind: Service
apiVersion: v1
metadata:
  name: trivy
  namespace: #@ data.values.trivy.namespace
spec:
  selector: #@ data.values.trivy.matchLabels
  ports:
  - name: web
    port: 8080
    targetPort: 8080
