---
apiVersion: v1
kind: Service
metadata:
  name: kube-proxy
  namespace: kube-system
  labels:
    app: kube-proxy
    jobLabel: kube-proxy
  annotations:
    kapp.k14s.io/disable-label-scoping: ""
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10249
      protocol: TCP
      targetPort: 10249
  selector:
    k8s-app: kube-proxy
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-proxy
  namespace: kube-system
  labels:
    app: kube-proxy
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: kube-proxy
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
  - port: http-metrics
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
