#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: #@ data.values.flux.namespace
spec:
  replicas: 1
  selector:
    matchLabels: #@ data.values.flux.fluxd.matchLabels
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/port: "3031"
      labels: #@ data.values.flux.fluxd.matchLabels
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      serviceAccountName: flux
      volumes:
      - name: git-key
        secret:
          secretName: flux-git-deploy
          defaultMode: 0400
      - name: git-keygen
        emptyDir:
          medium: Memory
      containers:
      - name: flux
        image: docker.io/fluxcd/flux:1.19.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        ports:
        - containerPort: 3030
        livenessProbe:
          httpGet:
            port: 3030
            path: /api/flux/v6/identity.pub
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            port: 3030
            path: /api/flux/v6/identity.pub
          initialDelaySeconds: 5
          timeoutSeconds: 5
        volumeMounts:
        - name: git-key
          mountPath: /etc/fluxd/ssh
          readOnly: true
        - name: git-keygen
          mountPath: /var/fluxd/keygen
        args:
        - --memcached-service=
        - --ssh-keygen-dir=/var/fluxd/keygen
        - #@ "--git-url={}".format(data.values.flux.git.repository)
        - #@ "--git-branch={}".format(data.values.flux.git.branch)
        - --git-label=flux-sync
        - #@ "--git-user={}".format(data.values.flux.git.user)
        - #@ "--git-email={}".format(data.values.flux.git.email)
        - --listen-metrics=:3031
        - --sync-garbage-collection
        - --git-poll-interval=120s
        - --sync-interval=120s
        - --manifest-generation=true
