#@data/values
---
#@overlay/match missing_ok=True
timezone: Europe/Berlin
tick:
  namespace: tick
  influxdb:
    matchLabels:
      service: influxdb
  chronograf:
    matchLabels:
      service: influxdb
  telegraf:
    matchLabels:
      service: influxdb
  volume:
    size: 1Gi
    storageClass: hcloud-volumes