#@ load("@ytt:data", "data")
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chronograf
  namespace: #@ data.values.tick.namespace
spec:
  replicas: 1
  selector:
    matchLabels: #@ data.values.tick.chronograf.matchLabels
  template:
    metadata:
      labels: #@ data.values.tick.chronograf.matchLabels
    spec:
      restartPolicy: Always
      containers:
      - name: main
        image: chronograf:alpine
        imagePullPolicy: Always
        env:
        - name: RESOURCES_PATH
          value: /usr/share/chronograf/resources
        - name: INFLUXDB_HOSTNAME
          value: http://influxdb:8086
        - name: INFLUXDB_USERNAME
          valueFrom:
            configMapKeyRef:
              key: influxdb-admin-name
              name: maas-dev
        - name: INFLUXDB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: influxdb-admin-pass
              name: maas-dev
        - name: INFLUXDB_DATABASE
          valueFrom:
            configMapKeyRef:
              key: influxdb-db-name
              name: maas-dev
        ports:
        - containerPort: 8888
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 250Mi
          requests:
            cpu: 250m
            memory: 100Mi
