apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: maas
    instance: dev
    service: chronograf
  name: chronograf
  namespace: maas-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      service: chronograf
  template:
    metadata:
      labels:
        app: maas
        instance: dev
        service: chronograf
    spec:
      containers:
      - env:
        - name: RESOURCES_PATH
          value: /usr/share/chronograf/resources
        - name: INFLUXDB_HOSTNAME
          value: http://influxdb:8086
        - name: INFLUXDB_USERNAME
          valueFrom:
            configMapKeyRef:
              key: influxdb-admin-name
              name: maas-dev
        - name: INFLUXDB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: influxdb-admin-pass
              name: maas-dev
        - name: INFLUXDB_DATABASE
          valueFrom:
            configMapKeyRef:
              key: influxdb-db-name
              name: maas-dev
        image: chronograf:alpine
        imagePullPolicy: Always
        name: chronograf
        ports:
        - containerPort: 8888
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 250Mi
          requests:
            cpu: 250m
            memory: 100Mi
        volumeMounts:
        - mountPath: /usr/share/chronograf/resources
          name: datasources
        - mountPath: /etc/localtime
          name: tz-config
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: chronograf
        name: datasources
      - hostPath:
          path: /usr/share/zoneinfo/Europe/Berlin
          type: ""
        name: tz-config
