#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-node-exporter
  namespace: #@ data.values.prometheus.operator.namespace
  labels:
    app: prometheus-node-exporter
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp-prometheus-node-exporter
  labels:     
    app: prometheus-node-exporter
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - node-exporter-prometheus-node-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp-prometheus-node-exporter
  labels:     
    app: prometheus-node-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-node-exporter-prometheus-node-exporter
subjects:
- kind: ServiceAccount
  name: node-exporter-prometheus-node-exporter
  namespace: #@ data.values.prometheus.operator.namespace
