#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    name: sealed-secrets-controller
  name: sealed-secrets-controller
  namespace: #@ data.values.kubeseal.namespace
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector: #@ data.values.kubeseal.matchLabels
  type: ClusterIP
