#@data/values
---
#@overlay/match missing_ok=True
timezone: Europe/Berlin
#@overlay/match missing_ok=True
domain: example.com
#@overlay/match missing_ok=True
gangway:
  namespace: gangway
  matchLabels:
    app: gangway
  dns:
    name: gangway
    lb: lb
  client:
    id: gangway
    secret: abc123
  session:
    secret: def456
