#@ load("@ytt:data", "data")
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: gitlab
spec:
  endpoints:
  - dnsName: #@ data.values.gitlab.fqdn
    recordTTL: 180
    recordType: CNAME
    targets:
    - lb.master.k8s.freecastle.eu
