apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: maas
    instance: devinfra
    service: loki
  name: loki
  namespace: maas-devinfra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  serviceName: loki-headless
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - args:
        - -config.file=/etc/loki/loki.yaml
        image: grafana/loki
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: http-metrics
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: loki
        ports:
        - containerPort: 3100
          name: http-metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: http-metrics
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /etc/loki
          name: config
        - mountPath: /data
          name: storage
          subPath: loki
        - mountPath: /etc/localtime
          name: tz-config
      restartPolicy: Always
      volumes:
      - name: config
        secret:
          defaultMode: 420
          secretName: loki
      - name: storage
        persistentVolumeClaim:
          claimName: nfs-storage-devinfra
      - hostPath:
          path: /usr/share/zoneinfo/Europe/Berlin
          type: ""
        name: tz-config
