#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token
  namespace: #@ data.values.certmanager.namespace
type: Opaque
stringData:
  token: #@ data.values.certmanager.cloudflare.key
