#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: #@ "webmaster@{}".format(data.values.domain)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        cloudflare:
          email: #@ data.values.cloudflare.email
          apiKeySecretRef:
            name: cloudflare-token
            key: token
      selector:
        dnsZones:
        - #@ data.values.domain
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: #@ "webmaster@{}".format(data.values.domain)
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        cloudflare:
          email: #@ data.values.cloudflare.email
          apiKeySecretRef:
            name: cloudflare-token
            key: token
      selector:
        dnsZones:
        - #@ data.values.domain
