#@data/values
---
#@overlay/match missing_ok=True
timezone: Europe/Berlin
#@overlay/match missing_ok=True
domain: example.com
#@overlay/match missing_ok=True
dex:
  namespace: dex
  matchLabels:
    app: dex
  dns:
    name: auth
    lb: lb
  gitlab:
    url: https://gitlab.com
    id: 123abc
    secret: 456def
  github:
    id: 234bcd
    secret: 567efg
#@overlay/match missing_ok=True
gangway:
  namespace: gangway
  matchLabels:
    app: gangway
  dns:
    name: login
    lb: lb
  client:
    id: gangway
    secret: abc123
  session:
    secret: def456
#@overlay/match missing_ok=True
openldap:
  namespace: openldap
  domain:
    dn: dc=example,dc=com
  matchLabels:
    app: openldap
  password:
    config: test123
    admin: test123
  dns:
    name: openldap
    lb: lb
#@overlay/match missing_ok=True
phpldapadmin:
  namespace: openldap
  matchLabels:
    app: phpldapadmin
  dns:
    name: phpldapadmin
    lb: lb
