#@ load("@ytt:data", "data")
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: #@ data.values.apiserver.name
  namespace: kube-system
spec:
  endpoints:
  - dnsName: #@ "k8s.{}".format(data.values.domain)
    recordTTL: 180
    recordType: A
    targets:
    - #@ data.values.apiserver.hostip
