#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-cluster
  namespace: prometheus
  labels:
    #@yaml/text-templated-strings
    (@= data.values.domain @)/loadbalancer: default
type: Opaque
stringData:
  traefik: #@ data.values.prometheus.htpasswd
