#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: server
  namespace: #@ data.values.loki.namespace
spec:
  replicas: 1
  selector:
    matchLabels: #@ data.values.loki.server.matchLabels
  serviceName: server-headless
  template:
    metadata:
      labels: #@ data.values.loki.server.matchLabels
    spec:
      restartPolicy: Always
      containers:
      - name: main
        image: grafana/loki
        imagePullPolicy: IfNotPresent
        args:
        - -config.file=/etc/loki/loki.yaml
        ports:
        - containerPort: 3100
          name: http-metrics
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: http-metrics
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: http-metrics
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /etc/loki
          name: config
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
      - name: config
        secret:
          defaultMode: 420
          secretName: loki
      - name: tz-config
        hostPath:
          path: #@ "/usr/share/zoneinfo/" + data.values.timezone
