#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: #@ data.values.externaldns.namespace
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels: #@ data.values.externaldns.matchLabels
  template:
    metadata:
      labels: #@ data.values.externaldns.matchLabels
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: eu.gcr.io/k8s-artifacts-prod/external-dns/external-dns:v0.7.1
        args:
        - --txt-owner-id=external-dns-crd
        - --source=crd
        - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
        - --crd-source-kind=DNSEndpoint
        - #@ "--domain-filter={}".format(data.values.domain)
        - --provider=cloudflare
        env:
        - name: CF_API_KEY
          valueFrom:
            secretKeyRef:
              name: cloudflare
              key: CF_API_KEY
        - name: CF_API_EMAIL
          valueFrom:
            secretKeyRef:
              name: cloudflare
              key: CF_API_EMAIL
        - name: TZ
          value: #@ data.values.timezone
