#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: #@ data.values.gitlab.namespace
spec:
  replicas: 1
  selector:
    matchLabels: #@ data.values.gitlab.redis.matchLabels
  template:
    metadata:
      labels: #@ data.values.gitlab.redis.matchLabels
    spec:
      containers:
      - name: main
        image: #@ "gitlab/gitlab-ce:{}-ce.0".format(data.values.gitlab.version)
        env:
        - name: GITLAB_OMNIBUS_CONFIG
          valueFrom:
            configMapKeyRef:
              name: redis
              key: GITLAB_OMNIBUS_CONFIG
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - mountPath: "/var/opt/gitlab"
          name: redis
          subPath: redis-data
        - mountPath: "/etc/gitlab"
          name: redis
          subPath: redis-config
        - mountPath: "/var/log/gitlab"
          name: redis
          subPath: redis-log
        - mountPath: /etc/localtime
          name: tz-config
      volumes:
      - name: redis
        emptyDir: {}
      - name: tz-config
        hostPath:
          path: #@ "/usr/share/zoneinfo/" + data.values.timezone
