#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: #@ data.values.gitlab.namespace
spec:
  replicas: 1
  selector:
    matchLabels: #@ data.values.gitlab.redis.matchLabels
  template:
    metadata:
      labels: #@ data.values.gitlab.redis.matchLabels
    spec:
      containers:
      - name: main
        image: #@ "gitlab/gitlab-ce:{}-ce.0".format(data.values.gitlab.version)
        env:
        - name: GITLAB_OMNIBUS_CONFIG
          valueFrom:
            configMapKeyRef:
              name: redis
              key: GITLAB_OMNIBUS_CONFIG
        ports:
        - name: redis
          containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: #@ data.values.gitlab.namespace
spec:
  selector: #@ data.values.gitlab.redis.matchLabels
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
