#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: #@ data.values.gitlab.namespace
spec:
  selector: #@ data.values.gitlab.redis.matchLabels
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
