#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki
  namespace: #@ data.values.loki.namespace
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: #@ data.values.loki.volume.storageClass
