apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea:1.5
          imagePullPolicy: Always
          ports:
          - name: web
            containerPort: 3000
          env:
          - name: SSH_PORT
            value: "2222"
          volumeMounts:
          - name: gitea-data
            mountPath: "/data"
      volumes:
        - name: gitea-data
          hostPath:
            path: /data/gitea-data
            type: DirectoryOrCreate
---
kind: Service
apiVersion: v1
metadata:
  name: gitea
spec:
  selector:
    app: gitea
  ports:
  - name: web
    port: 80
    targetPort: 3000