#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  namespace: #@ data.values.flux.namespace
spec:
  replicas: 1
  selector:
    matchLabels: #@ data.values.flux.memcached.matchLabels
  template:
    metadata:
      labels: #@ data.values.flux.memcached.matchLabels
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
      - name: memcached
        image: memcached:1.5.20
        imagePullPolicy: IfNotPresent
        args:
        - -m 512
        - -I 5m
        - -p 11211
        ports:
        - name: clients
          containerPort: 11211
        securityContext:
          runAsUser: 11211
          runAsGroup: 11211
          allowPrivilegeEscalation: false
