#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: dex
  namespace: #@ data.values.dex.namespace
type: Opaque
stringData:
  GITLAB_APPLICATION_ID: #@ data.values.dex.gitlabcom.id
  GITLAB_CLIENT_SECRET: #@ data.values.dex.gitlabcom.secret
  GITHUB_CLIENT_ID: #@ data.values.dex.github.id
  GITHUB_CLIENT_SECRET: #@ data.values.dex.github.secret
