#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: #@ data.values.metricsServer.namespace
spec:
  selector:
    matchLabels: #@ data.values.metricsServer.matchLabels
  template:
    metadata:
      labels: #@ data.values.metricsServer.matchLabels
    spec:
      serviceAccountName: metrics-server
      volumes:
      - name: tmp-dir
        emptyDir: {}
      - name: tz-config
        hostPath:
          path: #@ "/usr/share/zoneinfo/" + data.values.timezone
      containers:
      - name: metrics-server
        image: k8s.gcr.io/metrics-server-amd64:v0.3.6
        imagePullPolicy: Always
        volumeMounts:
        - name: tmp-dir
          mountPath: /tmp
        - name: tz-config
          mountPath: /etc/localtime
