#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: openldap
  namespace: #@ data.values.openldap.namespace
  labels: #@ data.values.openldap.matchLabels
type: Opaque
stringData:
  LDAP_ADMIN_PASSWORD: #@ data.values.openldap.password.admin
  LDAP_CONFIG_PASSWORD: #@ data.values.openldap.password.config
