#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: grafana
  namespace: #@ data.values.grafana.namespace
spec:
  secretName: certificate-grafana
  duration: 2160h
  renewBefore: 360h
  commonName: #@ data.values.grafana.fqdn
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
  - server auth
  - client auth
  dnsNames:
  - #@ data.values.grafana.fqdn
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer