apiVersion: v1
data:
  docker.cnf: |
    [mysqld]
    skip-host-cache
    skip-name-resolve
  mysql.cnf: |
    [mysqld]
    max_connections = 50
kind: ConfigMap
metadata:
  labels:
    app: maas
    instance: dev
    service: mysql-grafana
  name: mysql-grafana
  namespace: maas-dev
