#@ load("@ytt:data", "data")
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: grafana
  namespace: #@ data.values.grafana.namespace
spec:
  endpoints:
  - dnsName: #@ data.values.grafana.fqdn
    recordTTL: 180
    recordType: CNAME
    targets:
    - #@ data.values.grafana.lb