#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: #@ data.values.grafana.namespace
type: Opaque
stringData:
  admin-pass: #@ data.values.grafana.admin.password
  database-name: #@ data.values.grafana.database.name
  database-user: #@ data.values.grafana.database.username
  database-pass: #@ data.values.grafana.database.password
