#@data/values
---
#@overlay/match missing_ok=True
timezone: Europe/Berlin
#@overlay/match missing_ok=True
domain: example.com
grafana:
  namespace: grafana
  db:
    matchLabels:
      pod: mysql-grafana
  server:
    matchLabels:
      pod: grafana
  database:
    name: grafana
    username: grafana
    password: test123
  fqdn: grafana.example.com
  url: https://grafana.example.com
  lb: lb.example.com
  admin:
    password: test123
