---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hcloud-volumes
