#@ load("@ytt:data", "data")
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: shellinabox
  namespace: #@ data.values.siab.namespace
spec:
  entryPoints:
  - http
  routes:
  - match: #@ "Host(`{}`)".format(data.values.siab.fqdn)
    kind: Rule
    priority: 12
    services:
    - name: shellinabox
      port: 80
      strategy: RoundRobin
