#@data/values
---
#@overlay/match missing_ok=True
timezone: Europe/Berlin
nginx:
  port: 80
  tag: latest
  matchLabels:
    pod: nginx
  domain: example.io
  fqdn: nginx.example.io
  lb: lb.example.io
