#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db
  namespace: #@ data.values.gitlab.namespace
data:
  install_extensions.sql: |
    CREATE EXTENSION IF NOT EXISTS pg_trgm;
