#@ load("@ytt:data", "data")
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: db
  namespace: #@ data.values.gitlab.namespace
spec:
  schedule: "@daily"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: main
            image: #@ "postgres:{}".format(data.values.gitlab.db.version)
            command:
            - /bin/sh
            - -c
            args:
            - find /var/log/postgresql/data/pg_log/ -type f -name postgresql-\*.log -mtime 2 -exec rm {} \;
          restartPolicy: OnFailure
