#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: #@ data.values.gitlab.namespace
spec:
  replicas: 1
  selector:
    matchLabels: #@ data.values.gitlab.db.matchLabels
  template:
    metadata:
      labels: #@ data.values.gitlab.db.matchLabels
    spec:
      volumes:
      - name: db
        emptyDir: {}
      - name: tz-config
        hostPath:
          path: #@ "/usr/share/zoneinfo/" + data.values.timezone
      containers:
      - name: main
        image: #@ "postgres:{}".format(data.values.gitlab.db.version)
        args:
        - -c
        - logging_collector=off
        env:
        - name: POSTGRES_DB
          value: gitlab
        - name: POSTGRES_USER
          value: gitlab
        - name: POSTGRES_PASSWORD
          value: #@ data.values.gitlab.db.password
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: db
          subPath: db-data
        - name: tz-config
          mountPath: /etc/localtime
        ports:
        - name: db
          containerPort: 5432
