#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: #@ data.values.gitlab.namespace
spec:
  replicas: 1
  selector:
    matchLabels: #@ data.values.gitlab.db.matchLabels
  template:
    metadata:
      labels: #@ data.values.gitlab.db.matchLabels
    spec:
      volumes:
      - name: init
        configMap:
          name: db
      - name: tz-config
        hostPath:
          path: #@ "/usr/share/zoneinfo/" + data.values.timezone
      containers:
      - name: main
        image: #@ "postgres:{}".format(data.values.gitlab.db.version)
        env:
        - name: POSTGRES_DB
          value: gitlab
        - name: POSTGRES_USER
          value: gitlab
        - name: POSTGRES_PASSWORD
          value: #@ data.values.gitlab.db.password
        volumeMounts:
        - name: init
          mountPath: /docker-entrypoint-initdb.d
        - name: tz-config
          mountPath: /etc/localtime
        ports:
        - name: db
          containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: #@ data.values.gitlab.namespace
spec:
  selector: #@ data.values.gitlab.db.matchLabels
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
