#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton
  namespace: #@ data.values.tekton.namespace
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: #@ data.values.tekton.volume.size
  storageClassName: #@ data.values.tekton.volume.storageClass
