#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-agent
  namespace: #@ data.values.drone.namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-agent
  template:
    metadata:
      labels:
        app: drone-agent
    spec:
      containers:
        - name: drone-agent
          image: #@ "drone/agent:{}".format(data.values.drone.version)
          imagePullPolicy: Always
          env:
          - name: DRONE_RPC_HOST
            value: #@ data.values.drone.fqdn
          - name: DRONE_RPC_PROTO
            value: #@ data.values.drone.protocol
          - name: DRONE_RPC_SECRET
            value: #@ data.values.drone.secret
          - name: DRONE_RUNNER_CAPACITY
            value: 1
          - name: DOCKER_HOST
            value: "tcp://localhost:2375"
        - name: dind
          image: docker:stable-dind
          args:
          - --host
          - 0.0.0.0:2375
          imagePullPolicy: Always
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 2375
          volumeMounts:
          - name: config
            mountPath: /etc/docker/daemon.json
            subPath: daemon.json
      volumes:
      - name: config
        configMap:
          name: dind