#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: gangway
  namespace: #@ data.values.gangway.namespace
type: Opaque
stringData:
  sesssionkey: #@ data.values.gangway.session.secret
