#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Service
metadata:
  labels: #@ data.values.prometheus.operator.matchLabels
  name: prometheus-operator
  namespace: #@ data.values.prometheus.operator.namespace
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector: #@ data.values.prometheus.operator.matchLabels
