#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-path-provisioner
  namespace: #@ data.values.localPathProvisioner.namespace
spec:
  replicas: 1
  selector:
    matchLabels: #@ data.values.localPathProvisioner.matchLabels
  template:
    metadata:
      labels: #@ data.values.localPathProvisioner.matchLabels
    spec:
      serviceAccountName: local-path-provisioner-service-account
      containers:
      - name: local-path-provisioner
        image: #@ "rancher/local-path-provisioner:v{}".format(data.values.localPathProvisioner.version)
        imagePullPolicy: IfNotPresent
        command:
        - local-path-provisioner
        - --debug
        - start
        - --config
        - /etc/config/config.json
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config/
        - name: tz-config
          mountPath: /etc/localtime
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
        - name: config-volume
          configMap:
            name: local-path-config
        - name: tz-config
          hostPath:
            path: #@ "/usr/share/zoneinfo/" + data.values.timezone
