#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ data.values.localPathProvisioner.namespace
  metadata:
    labels:
      name: #@ data.values.localPathProvisioner.namespace
