#@ load("@ytt:data", "data")
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: #@ data.values.localPathProvisioner.storageClassName
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
