#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phpldapadmin
  namespace: #@ data.values.phpldapadmin.namespace
  labels: #@ data.values.phpldapadmin.matchLabels
data:
  #@yaml/text-templated-strings
  PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'openldap': [{'server': [{'tls': False}]},{'login': [{'bind_id': 'cn=admin,(@= data.values.openldap.domain.dn @)'}]}]}]"
  PHPLDAPADMIN_HTTPS: "false"
  PHPLDAPADMIN_TRUST_PROXY_SSL: "true"
