#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: prometheus-cluster
  namespace: prometheus
spec:
  secretName: certificate-prometheus-cluster
  duration: 2160h
  renewBefore: 360h
  commonName: #@ "{}.{}".format(data.values.prometheus.dns.lb, data.values.domain)
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
  - server auth
  - client auth
  dnsNames:
  - #@ "{}.{}".format(data.values.prometheus.dns.lb, data.values.domain)
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer